dateModified: 1650025492
email:
  fromEmail: dean@oveio.io
  fromName: 'Craft3 Starter'
  transportType: craft\mail\transportadapters\Sendmail
meta:
  __names__:
    8d5b3ffd-ea97-46ea-86ad-9ad5f00b7fac: 'Craft3 Starter' # Craft3 Starter
    454d3a80-eac3-423a-a1a2-ae2744803e67: 'Craft3 Starter' # Craft3 Starter
    83876ca5-c524-47de-80d4-66e246118897: Common # Common
plugins:
  mix:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
system:
  edition: solo
  live: true
  name: 'Craft3 Starter'
  schemaVersion: 3.7.33
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
